# Generated by Django 4.2.30 on 2026-05-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, null=True, upload_to='banner_picture_slider/')),
                ('video', models.FileField(blank=True, null=True, upload_to='banner_video_slider/')),
                ('alternative_text', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banner_time', models.IntegerField(default=30)),
                ('above_text_banner', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_text_banner', models.CharField(blank=True, max_length=200, null=True)),
                ('warning_text_banner', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'banner management part',
                'db_table': 'banner_slider',
            },
        ),
    ]
