# Generated by Django 4.2.30 on 2026-05-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_category_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'post_category_table',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_banner_picture', models.FileField(upload_to='blog_post_picture/')),
                ('alternative_banner_picture', models.CharField(max_length=30)),
                ('video_banner', models.FileField(blank=True, null=True, upload_to='blog_post_video/')),
                ('post_name', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.post_category')),
            ],
            options={
                'db_table': 'post_table',
            },
        ),
    ]
