# Generated by Django 4.2.30 on 2026-05-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'post management'},
        ),
        migrations.AlterModelOptions(
            name='post_category',
            options={'verbose_name_plural': 'post category management'},
        ),
    ]
