# Generated by Django 4.2.30 on 2026-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_picture', models.FileField(blank=True, null=True, upload_to='school_commenter_picture/')),
                ('commenter_name', models.CharField(max_length=50)),
                ('commenter_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'school comments management',
                'db_table': 'school_comments_table',
            },
        ),
    ]
