# Generated by Django 4.2.30 on 2026-05-07 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_picture', models.FileField(upload_to='personal_document/personal_picture/')),
                ('certificate_iranian_picture', models.FileField(upload_to='personal_document/certificate_iranian/')),
                ('passport_picture', models.FileField(upload_to='personal_document/passport_picture/')),
                ('personal_iranian_id', models.CharField(max_length=10, unique=True)),
                ('personal_foreign_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('hbd', django_jalali.db.models.jDateTimeField()),
                ('father_name', models.CharField(max_length=50)),
                ('father_iranian_id', models.CharField(max_length=10)),
                ('father_certificate_iranian', models.FileField(upload_to='personal_document/father_certificate_iranian/')),
                ('father_card_melli_iranian', models.FileField(upload_to='personal_document/father_card_melli_iranian/')),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_iranian_id', models.CharField(max_length=10)),
                ('mother_certificate_iranian', models.FileField(upload_to='personal_document/mother_certificate_iranian/')),
                ('mother_card_melli_iranian', models.FileField(upload_to='personal_document/mother_card_melli_iranian/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Information Management',
                'db_table': 'student_information_table',
            },
        ),
        migrations.AddConstraint(
            model_name='studentinformation',
            constraint=models.UniqueConstraint(condition=models.Q(('personal_foreign_id__isnull', False)), fields=('personal_foreign_id',), name='unique_code_when_not_null'),
        ),
    ]
