# Generated by Django 4.2.30 on 2026-05-07 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEducationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_1', models.FileField(blank=True, null=True, upload_to=school.models.class1_path, validators=[school.models.validate_file_size])),
                ('class_2', models.FileField(blank=True, null=True, upload_to=school.models.class2_path, validators=[school.models.validate_file_size])),
                ('class_3', models.FileField(blank=True, null=True, upload_to=school.models.class3_path, validators=[school.models.validate_file_size])),
                ('class_4', models.FileField(blank=True, null=True, upload_to=school.models.class4_path, validators=[school.models.validate_file_size])),
                ('class_5', models.FileField(blank=True, null=True, upload_to=school.models.class5_path, validators=[school.models.validate_file_size])),
                ('class_6', models.FileField(blank=True, null=True, upload_to=school.models.class6_path, validators=[school.models.validate_file_size])),
                ('class_7', models.FileField(blank=True, null=True, upload_to=school.models.class7_path, validators=[school.models.validate_file_size])),
                ('class_8', models.FileField(blank=True, null=True, upload_to=school.models.class8_path, validators=[school.models.validate_file_size])),
                ('class_9', models.FileField(blank=True, null=True, upload_to=school.models.class9_path, validators=[school.models.validate_file_size])),
                ('class_10', models.FileField(blank=True, null=True, upload_to=school.models.class10_path, validators=[school.models.validate_file_size])),
                ('class_11', models.FileField(blank=True, null=True, upload_to=school.models.class11_path, validators=[school.models.validate_file_size])),
                ('class_12', models.FileField(blank=True, null=True, upload_to=school.models.class12_path, validators=[school.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
